displayName: Add header
type: middleware

import: github.com/Knight-7/addheader

summary: '[Demo] Add Request Header'

testData:
  Headers:
    X-Demo: test
    X-URL: '{{URL}}'
  Paths:
    model: "./model.conf"
    policy: "./policy.csv"